Feat/create task to update indexing of worlds
decentraland/places pull request #283
Opened 2023-06-15 14:57 UTC by braianj

2023-06-16 13:47 UTC, lauti7 approved these changes
LGTM, just one comment

2023-06-16 13:47 UTC, lauti7 commented on src/entities/World/task/verifyWorldsIndexing.ts
> +  )
Shouldn't be a `try {} catch(e) {}`?

2023-06-19 12:58 UTC, 2fd requested changes

2023-06-19 12:58 UTC, 2fd commented on src/entities/Place/model.ts
> +    const sqlNames = SQL`${join(names.map((item) => SQL`${item}`))}`
```suggestion
```

2023-06-19 12:58 UTC, 2fd commented on src/entities/Place/model.ts
> +    const sqlNames = SQL`${join(names.map((item) => SQL`${item}`))}`
```suggestion
```

2023-06-19 12:58 UTC, 2fd commented on src/entities/World/task/verifyWorldsIndexing.ts
> +      "https://dcl-name-stats.decentraland.org/should-index",
```suggestion
      env("WORLDS_INDEX_API", "https://dcl-name-stats.decentraland.org/should-index")
```

2023-06-19 12:58 UTC, 2fd commented on src/entities/World/task/verifyWorldsIndexing.ts
> +      .filter((world) => !!world) as string[]
```ts
    const shouldIndexNames = shouldIndex.data
      .filter((world) => world.shouldBeIndexed === true)
      .map((world) => world.dclName)
```

👀

2023-06-19 12:58 UTC, 2fd commented on src/entities/World/task/verifyWorldsIndexing.ts
> +      .filter((world) => !!world) as string[]
```ts
    const shouldNotIndexNames = shouldIndex.data
      .filter((world) => world.shouldBeIndexed !== true)
      .map((world) => world.dclName)
```

:eyes:

2023-06-19 12:58 UTC, 2fd commented on src/entities/World/task/processWorldsIndexing.ts
> +  if (worldsVerified.hasNonIndexNames) {
couldn't this be done with only one query?

2023-06-19 19:43 UTC, 2fd approved these changes

2023-06-19 19:43 UTC, 2fd commented on src/entities/Place/model.ts
> +  join,
```suggestion
```

2023-06-19 19:51 UTC, merged