chore: Add debounce to search and metrics
decentraland/places pull request #314
Opened 2023-07-21 20:05 UTC by jmoguilevsky

2023-07-24 14:00 UTC, braianj requested changes

2023-07-24 14:00 UTC, braianj commented on src/components/Layout/SearchInput.tsx
> +  const debouncedHandleChange = useMemo(() => debounce(handleChange, 350), [])
WDYT about useCallback?

2023-07-24 14:00 UTC, braianj commented on src/components/Place/PlaceCard/PlaceCard.tsx
> +        place: place?.id,
I think we use place for the position in the site, like `world_list`, that would be `place_id` and maybe the place should came from props ¿?

2023-07-24 14:00 UTC, braianj commented on src/components/Place/PlaceCard/PlaceCard.tsx
> +      <a className="place-card__cover" href={href} onClick={handleClickCard}>
There is a component `<Link>` that has tracking embed in it (you can send tracking data as props) and navigate too

2023-07-24 14:00 UTC, braianj commented on src/pages/worlds.tsx
> +        place: SegmentPlace.Worlds,
maybe `SegmentPlace.WorldsSearch`?

2023-07-25 14:46 UTC, jmoguilevsky commented on src/pages/places.tsx
> +        place: SegmentPlace.Places,
The place is places, the event is places search in my opinion

2023-07-25 14:46 UTC, jmoguilevsky commented on src/pages/worlds.tsx
> +        place: SegmentPlace.Worlds,
Same as places, the place is worlds

2023-07-26 17:44 UTC, braianj approved these changes

2023-07-26 19:09 UTC, merged