feat: UI redesign for likes information
decentraland/places pull request #317
Opened 2023-07-31 19:03 UTC by lauti7

this PR:
- remove repeated stuff between components
- creates reusable components
- displays likes info in a new way
![Screenshot 2023-07-31 at 12 18 53](https://github.com/decentraland/places/assets/26555310/0617c50f-9ab7-4bbc-92e2-574d51fd5c6d)
![Screenshot 2023-07-31 at 13 32 11](https://github.com/decentraland/places/assets/26555310/766f1f95-e51b-46ed-9103-da5943adc99d)

2023-07-31 21:11 UTC, braianj commented on src/components/shared/Likes.tsx
> +        <p style={{ color: "#161418", marginLeft: "5px" }}>
please do not use inline style, only if it is really necessary.

2023-07-31 21:11 UTC, braianj commented on src/components/shared/Likes.tsx
> +          <span style={{ color: "#726d7c" }}>({likesCount})</span>
please do not use inline style, only if it is really necessary.

2023-07-31 21:11 UTC, braianj commented on src/components/shared/Likes.tsx
> +      }}
please do not use inline style, only if it is really necessary.

2023-07-31 21:11 UTC, braianj commented on src/components/shared/LocationDescription.tsx
>  export type PlaceDescriptionProps = {
I think that if we change the file name from `PlaceDescription` to `LocationDescription`, we should also change the name of the properties, the name of the function (and maybe the names of all the classes), to make a cleaner job.

2023-08-03 18:34 UTC, 2fd requested changes
the entire `src/components/shared` directory is a red flag. Even if it's obvious to you now, is not evident what its component represents or should be, it is just a way to hide disorganization. We can discuss if there is a better abstraction for this, but please do not create a `shared` or `commons` directory unless there is absolutely no  other way

2023-08-03 18:34 UTC, 2fd commented on src/components/Icon/ThumbDown.tsx
> +        stroke="black"
color for the components should go on css

```suggestion
```

2023-08-03 18:34 UTC, 2fd commented on src/components/Icon/ThumbDown.tsx
> +        stroke="black"
color for the components should go on CSS

```suggestion
```

2023-08-03 18:34 UTC, 2fd commented on src/components/Button/LikeBox.tsx
This abstraction seems reasonable, but the difference between the Like and Dislike buttons are the same as between the Like and the Favorite button. We should simultaneously create an abstraction for all BoxButton or leave it simple for the next dev that needs to refactor it.

2023-08-03 18:34 UTC, 2fd commented on static/images/places/info.svg
we prefer to use `<svg />` components instead of `svg` image to control their color with CSS, please move this to react

2023-08-03 18:34 UTC, 2fd commented on src/pages/world.tsx
> -          <WorldDescription
We are expecting that modification over the definitions and info of a world, that is why it was on a different component, please revert this change now so we don't have to do it later

2023-08-04 13:07 UTC, lauti7 commented on src/components/Button/LikeBox.tsx
Actually, they are no longer the same because of the styles. Before this, the Favorite and Like buttons shared the same styles. But now, they don't share CSS as before and it's more challenging to create an abstraction for them or it's possible but the code will look weird for the next devs.

2023-08-04 14:53 UTC, braianj commented on src/components/Button/LikeBox.tsx
In fact we can use the same component. The only difference is whether or not the text is displayed and whether the box is round or square. These are properties that could be passed on. 
From my point of view we could merge the three and pass by property these differences.

2023-08-07 16:30 UTC, braianj requested changes

2023-08-07 16:30 UTC, braianj commented on src/components/Place/PlaceDescription/PlaceDescription.tsx
> +export default React.memo(function LocationDescription(
This show be renamed to `PlaceDescription` as the File name is `PlaceDescription`

2023-08-07 19:00 UTC, braianj approved these changes
LGTM 👍

2023-08-07 19:01 UTC, merged